# Generated by Django 5.1.6 on 2025-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_datos_personales'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_personales',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
