# Generated by Django 5.1.6 on 2025-12-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_datos_personales_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.modulo'),
        ),
    ]
