# Generated by Django 5.1.6 on 2025-12-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistencia_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_personales',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
