# Generated by Django 5.1.6 on 2025-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_datos_personales_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
