# Generated by Django 5.1.6 on 2025-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_programa_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
