# Generated by Django 5.1.6 on 2025-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_modulo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
